version: '3'
services:
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  portfolio:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/portfolio
    ports:
      - "3333:3000"
    depends_on:
      - pg
    tty: true
    stdin_open: true
