version: '3'
volumes:
  mysql_8_0-data:
  redis-data:
  vendor_bundle_2_5_1:
  vendor_assets_2_7:
  node_modules:

services:
  redis:
    image: "redis:latest"
    networks:
      - default
    ports:
      - "6666:6379"
    volumes:
      - redis-data:/var/lib/redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3300:3306"
    volumes:
      - mysql_8_0-data:/var/lib/mysql

  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3333:3000"
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      REDIS_URL: "redis://redis:6666"
    volumes:
      - .:/portfolio
      - /portfolio/log
      - /portfolio/tmp
      - vendor_bundle_2_5_1:/portfolio/vendor/bundle
      - vendor_assets_2_7:/portfolio/vendor/assets
      - node_modules:/portfolio/node_modules
    depends_on:
      - mysql
      - redis
    networks:
      - default
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
