version: 2.1
jobs:
  rspec:
    working_directory: ~/portfolio
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.yml" >> $BASH_ENV
      - run:
          name: Start containers and verify it is working
          command: |
            set -x
            docker-compose up -d
            docker exec portfolio_portfolio_1 curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3333
      - run:
          name: Setup database
          command: |
            docker-compose exec portfolio bash
            bundle exec rails db:create
            bundle exec rails db:schema:load
      - run:
          name: Run rspec
          command: | 
            bundle exec rails spec

  rubocop:
    working_directory: ~/portfolio
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

orbs:
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@1.9.1
workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      - rubocop
